---
# This is a demo for Ansible playbooks
# http://ansible.github.com
# 
# this demo playbook is for CentOS6 + EPEL
# it could configure yum.repos.d via templates
# but didn't want to reconfigure any system
# you might run it on without asking.
#
# Creative Commons 3.0
# Michael DeHaan <michael.dehaan@gmail.com>

##########################################################
# Configure all hosts to be monitored
# (and just for this demo, also include the monitoring server
# in that list)

- hosts: real-workers1:masters
  user: updates
  sudo: yes
  tasks:
     # what roles to apply?
     - include: tasks/common.yml
     - include: tasks/monitored_server.yml
  handlers:
     - include: handlers/handlers.yml

############################################################
# Configure the monitoring server.  Note that this assumes
# CentOS 6 with EPEL configured.  Ansible can obviously
# configure yum.repos.d but this is left off to keep
# the example short.

- hosts: masters
  user: updates
  sudo: yes
  vars:
     # ganglia requires a node running gmetad to talk to.
     cluster_groups:
       - real-workers1
       - masters
  tasks:
     # what roles to apply?
     - include: tasks/common.yml
     - include: tasks/monitoring_server.yml
  handlers:
    - include: handlers/handlers.yml

    

