# this file defines behavior for the 'monitoring server' class of nodes

- name: install {{ item }}
  yum: pkg={{ item }} state=installed
  with_items:
    - ganglia
    - ganglia-gmetad

- name: install ganglia-web
  yum: pkg=ganglia-web state=installed
  notify:
     - restart httpd

- name: configure gmetad
  template: src=templates/etc/ganglia/gmetad.conf dest=/etc/ganglia/gmetad.conf
  notify:
      - restart gmetad

- name: ensure that ganglia services are running
  service: name={{ item }} state=running
  with_items:
      - gmond
      - httpd
      - gmetad

